services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped 